#!/bin/bash

# Deploy Edge Function Script
# This script shows how to deploy the Edge Function

echo "🚀 Edge Function Deployment Instructions"
echo "========================================"
echo ""
echo "The Edge Function needs to be redeployed with the fixed email configuration."
echo ""
echo "📋 Manual Deployment Steps:"
echo ""
echo "1. Go to your Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/cmcfeiskfdbsefzqywbk"
echo ""
echo "2. Navigate to Edge Functions:"
echo "   - Click 'Edge Functions' in the left sidebar"
echo "   - Find 'otp-password-reset' function"
echo ""
echo "3. Update the function:"
echo "   - Click on the function name"
echo "   - Click 'Edit Function' or 'Deploy'"
echo "   - Copy the contents from: supabase/functions/otp-password-reset/index.ts"
echo "   - Paste and deploy"
echo ""
echo "🔧 Alternative: Use Supabase CLI (if available):"
echo "   supabase functions deploy otp-password-reset"
echo ""
echo "✅ After deployment, the OTP emails will work correctly!"
echo "   Users will receive beautiful OTP emails instead of reset links."
echo ""